pkgname = "dbmodel"
output = "infrastructure/database/dbmodel"

wipe     = true
no-tests = true

[mysql]
dbname="legato_db"
host="legato_mysqldb"
port=3306
user="root"
pass="password"
sslmode="false"
